// Code generated by protoc-gen-go. DO NOT EDIT.
// source: grapherino.proto

package grapherino

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Connection struct {
	To                   string   `protobuf:"bytes,1,opt,name=to,proto3" json:"to,omitempty"`
	Weight               int64    `protobuf:"varint,2,opt,name=weight,proto3" json:"weight,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Connection) Reset()         { *m = Connection{} }
func (m *Connection) String() string { return proto.CompactTextString(m) }
func (*Connection) ProtoMessage()    {}
func (*Connection) Descriptor() ([]byte, []int) {
	return fileDescriptor_63287bc0525da1b6, []int{0}
}

func (m *Connection) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Connection.Unmarshal(m, b)
}
func (m *Connection) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Connection.Marshal(b, m, deterministic)
}
func (m *Connection) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Connection.Merge(m, src)
}
func (m *Connection) XXX_Size() int {
	return xxx_messageInfo_Connection.Size(m)
}
func (m *Connection) XXX_DiscardUnknown() {
	xxx_messageInfo_Connection.DiscardUnknown(m)
}

var xxx_messageInfo_Connection proto.InternalMessageInfo

func (m *Connection) GetTo() string {
	if m != nil {
		return m.To
	}
	return ""
}

func (m *Connection) GetWeight() int64 {
	if m != nil {
		return m.Weight
	}
	return 0
}

type Connections struct {
	Connections          []*Connection `protobuf:"bytes,1,rep,name=connections,proto3" json:"connections,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *Connections) Reset()         { *m = Connections{} }
func (m *Connections) String() string { return proto.CompactTextString(m) }
func (*Connections) ProtoMessage()    {}
func (*Connections) Descriptor() ([]byte, []int) {
	return fileDescriptor_63287bc0525da1b6, []int{1}
}

func (m *Connections) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Connections.Unmarshal(m, b)
}
func (m *Connections) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Connections.Marshal(b, m, deterministic)
}
func (m *Connections) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Connections.Merge(m, src)
}
func (m *Connections) XXX_Size() int {
	return xxx_messageInfo_Connections.Size(m)
}
func (m *Connections) XXX_DiscardUnknown() {
	xxx_messageInfo_Connections.DiscardUnknown(m)
}

var xxx_messageInfo_Connections proto.InternalMessageInfo

func (m *Connections) GetConnections() []*Connection {
	if m != nil {
		return m.Connections
	}
	return nil
}

type NetworkMap struct {
	Nodes                map[string]*Connections `protobuf:"bytes,1,rep,name=nodes,proto3" json:"nodes,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}                `json:"-"`
	XXX_unrecognized     []byte                  `json:"-"`
	XXX_sizecache        int32                   `json:"-"`
}

func (m *NetworkMap) Reset()         { *m = NetworkMap{} }
func (m *NetworkMap) String() string { return proto.CompactTextString(m) }
func (*NetworkMap) ProtoMessage()    {}
func (*NetworkMap) Descriptor() ([]byte, []int) {
	return fileDescriptor_63287bc0525da1b6, []int{2}
}

func (m *NetworkMap) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NetworkMap.Unmarshal(m, b)
}
func (m *NetworkMap) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NetworkMap.Marshal(b, m, deterministic)
}
func (m *NetworkMap) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NetworkMap.Merge(m, src)
}
func (m *NetworkMap) XXX_Size() int {
	return xxx_messageInfo_NetworkMap.Size(m)
}
func (m *NetworkMap) XXX_DiscardUnknown() {
	xxx_messageInfo_NetworkMap.DiscardUnknown(m)
}

var xxx_messageInfo_NetworkMap proto.InternalMessageInfo

func (m *NetworkMap) GetNodes() map[string]*Connections {
	if m != nil {
		return m.Nodes
	}
	return nil
}

type ExchangeReq struct {
	Id                   string       `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Connections          *Connections `protobuf:"bytes,2,opt,name=connections,proto3" json:"connections,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *ExchangeReq) Reset()         { *m = ExchangeReq{} }
func (m *ExchangeReq) String() string { return proto.CompactTextString(m) }
func (*ExchangeReq) ProtoMessage()    {}
func (*ExchangeReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_63287bc0525da1b6, []int{3}
}

func (m *ExchangeReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ExchangeReq.Unmarshal(m, b)
}
func (m *ExchangeReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ExchangeReq.Marshal(b, m, deterministic)
}
func (m *ExchangeReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ExchangeReq.Merge(m, src)
}
func (m *ExchangeReq) XXX_Size() int {
	return xxx_messageInfo_ExchangeReq.Size(m)
}
func (m *ExchangeReq) XXX_DiscardUnknown() {
	xxx_messageInfo_ExchangeReq.DiscardUnknown(m)
}

var xxx_messageInfo_ExchangeReq proto.InternalMessageInfo

func (m *ExchangeReq) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *ExchangeReq) GetConnections() *Connections {
	if m != nil {
		return m.Connections
	}
	return nil
}

type ExchangeRes struct {
	Id                   string        `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Connections          []*Connection `protobuf:"bytes,2,rep,name=connections,proto3" json:"connections,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *ExchangeRes) Reset()         { *m = ExchangeRes{} }
func (m *ExchangeRes) String() string { return proto.CompactTextString(m) }
func (*ExchangeRes) ProtoMessage()    {}
func (*ExchangeRes) Descriptor() ([]byte, []int) {
	return fileDescriptor_63287bc0525da1b6, []int{4}
}

func (m *ExchangeRes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ExchangeRes.Unmarshal(m, b)
}
func (m *ExchangeRes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ExchangeRes.Marshal(b, m, deterministic)
}
func (m *ExchangeRes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ExchangeRes.Merge(m, src)
}
func (m *ExchangeRes) XXX_Size() int {
	return xxx_messageInfo_ExchangeRes.Size(m)
}
func (m *ExchangeRes) XXX_DiscardUnknown() {
	xxx_messageInfo_ExchangeRes.DiscardUnknown(m)
}

var xxx_messageInfo_ExchangeRes proto.InternalMessageInfo

func (m *ExchangeRes) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *ExchangeRes) GetConnections() []*Connection {
	if m != nil {
		return m.Connections
	}
	return nil
}

func init() {
	proto.RegisterType((*Connection)(nil), "grapherino.Connection")
	proto.RegisterType((*Connections)(nil), "grapherino.Connections")
	proto.RegisterType((*NetworkMap)(nil), "grapherino.NetworkMap")
	proto.RegisterMapType((map[string]*Connections)(nil), "grapherino.NetworkMap.NodesEntry")
	proto.RegisterType((*ExchangeReq)(nil), "grapherino.ExchangeReq")
	proto.RegisterType((*ExchangeRes)(nil), "grapherino.ExchangeRes")
}

func init() {
	proto.RegisterFile("grapherino.proto", fileDescriptor_63287bc0525da1b6)
}

var fileDescriptor_63287bc0525da1b6 = []byte{
	// 281 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x92, 0x4f, 0x4b, 0xf4, 0x30,
	0x10, 0xc6, 0x49, 0xcb, 0x2e, 0xef, 0x3b, 0x01, 0x59, 0xe6, 0xb0, 0x96, 0x3d, 0xd5, 0x9e, 0x7a,
	0xb1, 0x87, 0x2a, 0x58, 0xc5, 0x9b, 0x2c, 0x0b, 0x82, 0x0b, 0xe6, 0xa2, 0xd7, 0xda, 0x86, 0x36,
	0xac, 0x24, 0x35, 0x8d, 0xae, 0xfb, 0x4d, 0xfc, 0xb8, 0xd2, 0xdd, 0xad, 0x49, 0xfd, 0x83, 0xde,
	0x32, 0x93, 0x5f, 0x9e, 0x99, 0xe7, 0x21, 0x30, 0xa9, 0x74, 0xde, 0xd4, 0x5c, 0x0b, 0xa9, 0x92,
	0x46, 0x2b, 0xa3, 0x10, 0x6c, 0x27, 0x3a, 0x05, 0xb8, 0x52, 0x52, 0xf2, 0xc2, 0x08, 0x25, 0xf1,
	0x00, 0x3c, 0xa3, 0x02, 0x12, 0x92, 0xf8, 0x3f, 0xf3, 0x8c, 0xc2, 0x29, 0x8c, 0xd7, 0x5c, 0x54,
	0xb5, 0x09, 0xbc, 0x90, 0xc4, 0x3e, 0xdb, 0x57, 0xd1, 0x02, 0xa8, 0x7d, 0xd5, 0x62, 0x06, 0xb4,
	0xb0, 0x65, 0x40, 0x42, 0x3f, 0xa6, 0xe9, 0x34, 0x71, 0x06, 0x5b, 0x9a, 0xb9, 0x68, 0xf4, 0x46,
	0x00, 0x96, 0xdc, 0xac, 0x95, 0x5e, 0xdd, 0xe4, 0x0d, 0x9e, 0xc1, 0x48, 0xaa, 0x92, 0xf7, 0x12,
	0x47, 0xae, 0x84, 0xc5, 0x92, 0x65, 0xc7, 0xcc, 0xa5, 0xd1, 0x1b, 0xb6, 0xe3, 0x67, 0xb7, 0x00,
	0xb6, 0x89, 0x13, 0xf0, 0x57, 0x7c, 0xb3, 0xf7, 0xd1, 0x1d, 0xf1, 0x18, 0x46, 0x2f, 0xf9, 0xe3,
	0x33, 0xdf, 0xfa, 0xa0, 0xe9, 0xe1, 0xf7, 0xbb, 0xb5, 0x6c, 0x47, 0x5d, 0x78, 0x19, 0x89, 0xee,
	0x81, 0xce, 0x5f, 0x8b, 0x3a, 0x97, 0x15, 0x67, 0xfc, 0xa9, 0x8b, 0x46, 0x94, 0x7d, 0x34, 0xa2,
	0xc4, 0xf3, 0xa1, 0xe7, 0x5f, 0x74, 0x07, 0xa6, 0xef, 0x5c, 0xe5, 0xf6, 0x8b, 0x72, 0xf6, 0x59,
	0xf9, 0xaf, 0x69, 0xa6, 0xd7, 0x00, 0x8b, 0x0f, 0x0a, 0x2f, 0xe1, 0x5f, 0x3f, 0x06, 0x07, 0x8b,
	0x39, 0xb6, 0x66, 0x3f, 0x5c, 0xb4, 0x0f, 0xe3, 0xed, 0x5f, 0x39, 0x79, 0x0f, 0x00, 0x00, 0xff,
	0xff, 0x0e, 0xa6, 0xf6, 0xb1, 0x3f, 0x02, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// GrapherinoClient is the client API for Grapherino service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type GrapherinoClient interface {
	Exchange(ctx context.Context, in *ExchangeReq, opts ...grpc.CallOption) (*ExchangeRes, error)
}

type grapherinoClient struct {
	cc grpc.ClientConnInterface
}

func NewGrapherinoClient(cc grpc.ClientConnInterface) GrapherinoClient {
	return &grapherinoClient{cc}
}

func (c *grapherinoClient) Exchange(ctx context.Context, in *ExchangeReq, opts ...grpc.CallOption) (*ExchangeRes, error) {
	out := new(ExchangeRes)
	err := c.cc.Invoke(ctx, "/grapherino.Grapherino/Exchange", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GrapherinoServer is the server API for Grapherino service.
type GrapherinoServer interface {
	Exchange(context.Context, *ExchangeReq) (*ExchangeRes, error)
}

// UnimplementedGrapherinoServer can be embedded to have forward compatible implementations.
type UnimplementedGrapherinoServer struct {
}

func (*UnimplementedGrapherinoServer) Exchange(ctx context.Context, req *ExchangeReq) (*ExchangeRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Exchange not implemented")
}

func RegisterGrapherinoServer(s *grpc.Server, srv GrapherinoServer) {
	s.RegisterService(&_Grapherino_serviceDesc, srv)
}

func _Grapherino_Exchange_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ExchangeReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GrapherinoServer).Exchange(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grapherino.Grapherino/Exchange",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GrapherinoServer).Exchange(ctx, req.(*ExchangeReq))
	}
	return interceptor(ctx, in, info, handler)
}

var _Grapherino_serviceDesc = grpc.ServiceDesc{
	ServiceName: "grapherino.Grapherino",
	HandlerType: (*GrapherinoServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Exchange",
			Handler:    _Grapherino_Exchange_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "grapherino.proto",
}
